apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: code-challenge
  labels:
    app: wp-blog
spec:
  ports:
    - port: 80
  selector:
    app: wp-blog
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: code-challenge
  labels:
    app: wp-blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# TODO: complete the wordpress deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: code-challenge
  labels:
    app: wp-blog
spec:
  selector:
    matchLabels:
      app: wp-blog
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp-blog
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wp-blog
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-pass
              key: password
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        ports:
        - containerPort: 80
          name: wp-blog
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
